name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main
  workflow_dispatch:
    inputs:
      stage:
        description: 'Select the stage to run'
        required: true
        default: 'test'
        options:
          - test
          - dev
          - deploy

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.stage == 'test' }}
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

  dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.stage == 'dev' }}
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Start the development environment
      - name: Start development server
        run: npm run dev  # Replace with your actual dev command

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.stage == 'deploy' }}
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy to staging (replace with actual deploy commands)
      - name: Deploy to staging
        run: |
          echo "Deploying to staging server..."
          # Add your actual deployment commands here (e.g., using AWS CLI, Docker, etc.)
