name: Deploy and Manage mt_app on EC2

on:
  workflow_dispatch:
    inputs:
      deploy_mt_app:
        description: 'Execute commands inside running mt_app container'
        required: true
        default: false
        type: boolean

jobs:
  deploy_mt_app:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy_mt_app == 'true' }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Execute commands inside running mt_app container
      run: |
        ssh -o StrictHostKeyChecking=no -T ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Execute commands inside the running mt_app container
          CONTAINER_ID=$(sudo docker ps -q -f "name=mt_app")

          if [ -z "$CONTAINER_ID" ]; then
            echo "mt_app container is not running. Exiting."
            exit 1
          fi

          # Execute any desired command inside the running container
          sudo docker exec -i $CONTAINER_ID bash -c 'echo "Custom command executed inside mt_app container"'

        EOF
