name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main
  workflow_dispatch:
    inputs:
      stage:
        description: 'Select the stage to run'
        required: true
        default: 'test'
        options:
          - test
          - deploy

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.stage == 'test' || github.event_name == 'push' || github.event_name == 'pull_request' }}

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.stage == 'deploy' || github.event_name == 'push' || github.event_name == 'pull_request' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Deploy to staging
        run: |
          echo "Deploying to staging server..."
          # Replace with actual deployment commands, e.g., using AWS CLI, Docker, or other deployment tools
