name: Deploy Nginx to EC2

on:
  push:
    branches:
      - main
      - stage # Trigger workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Add your private SSH key to GitHub secrets

    - name: Deploy Nginx to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}  # The public IP or DNS of your EC2 instance
        EC2_USER: ${{ secrets.EC2_USER }}  # The user to SSH as (e.g., ubuntu for Ubuntu AMIs)
      run: |
        # Transfer the Docker Compose file to the EC2 instance
        echo "Creating a Docker Compose file for Nginx..."
        echo "version: '3.8'
        services:
          nginx:
            image: nginx:latest
            ports:
              - 80:80" > docker-compose.yml

        echo "Copying the Docker Compose file to the EC2 instance..."
        scp -o StrictHostKeyChecking=no docker-compose.yml $EC2_USER@$EC2_HOST:~/

        # Connect to EC2 and deploy the container
        echo "Connecting to EC2 and starting the Nginx container..."
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
        docker compose down || true  # Stop any existing container
        docker compose up -d         # Start the Nginx container
        EOF
