name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Run tests'
        required: false
        type: boolean
        default: false
      dev:
        description: 'Run dev environment'
        required: false
        type: boolean
        default: false
      deploy:
        description: 'Run deploy'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.dev == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start development server
        run: npm run dev  # Replace with your actual dev command

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Replace with your actual deployment commands (e.g., AWS CLI, Docker, etc.)
