name: Deploy and Manage Nginx on EC2

on:
  workflow_dispatch:
    inputs:
      deploy_nginx:
        description: 'Deploy Nginx to EC2'
        required: true
        default: false
        type: boolean
      change_default_page:
        description: 'Change default Nginx page'
        required: true
        default: false
        type: boolean

jobs:
  deploy_nginx:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy_nginx == 'true' }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Deploy Nginx to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -T ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Pull the latest Nginx image from Docker Hub
          sudo docker pull nginx:latest

          # Stop and remove any existing container
          sudo docker stop nginx-container || true
          sudo docker rm nginx-container || true

          # Run the Nginx container
          sudo docker run -d --name nginx-container -p 80:80 nginx:latest

          # Verify that the container is running
          sudo docker ps
        EOF

  change_default_page:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.change_default_page == 'true' }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Change Default Nginx Page
      run: |
        ssh -o StrictHostKeyChecking=no -T ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Change default Nginx page
          echo "<html><h1>Welcome to My Custom Nginx Page</h1></html>" | sudo tee /usr/share/nginx/html/index.html

          # Restart Nginx container to apply changes
          sudo docker restart nginx-container

          # Verify that the page is updated
          curl localhost
        EOF
