name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      pull_branch:
        description: 'Pull the branch from Git'
        required: true
        default: 'false'
        type: boolean  # Checkbox-like input (true/false)
      docker_build:
        description: 'Run Docker build and up'
        required: true
        default: 'false'
        type: boolean  # Checkbox-like input (true/false)
      extra_commands:
        description: 'Extra commands to execute inside the container (e.g. php artisan migrate)'
        required: false
        default: ''
        type: string  # Text input for extra commands to run inside the container

jobs:
  ci_cd_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Branch
        if: ${{ github.event.inputs.pull_branch == 'true' }}
        run: |
          echo "Pulling the production branch..."
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${server_user}@${server_ip} "cd ${app_root} && git pull origin production"

      - name: Docker Build
        if: ${{ github.event.inputs.docker_build == 'true' }}
        run: |
          echo "Building Docker containers..."
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${server_user}@${server_ip} "cd ${app_root} && docker-compose -f ${app_root}/docker-compose.yml up -d --build"

      - name: Execute Extra Commands
        if: ${{ github.event.inputs.extra_commands != '' }}
        run: |
          echo "Executing extra commands inside the container..."
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${server_user}@${server_ip} "docker exec -i crm_marshub_prod php ${github.event.inputs.extra_commands}"
