name: SSH into PROXY_Servers

on:
  push:
    branches:
      - main

jobs:
  ssh-into-servers:
    runs-on: ubuntu-latest

    steps:
      # SSH into the first server and then into the second server
      - name: SSH into the server
        run: |
          ssh -o StrictHostKeyChecking=no root@65.108.2.208 << 'EOF'
            echo "Successfully connected to the public server!"
          EOF
