name: SSH into Public and Private Servers

on:
  push:
    branches:
      - main

jobs:
  ssh-into-servers:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH for Public Server
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: SSH into Public Server and Private Server
        run: |
          # Force pseudo-terminal allocation with -tt and use single SSH command
          ssh -tt -o StrictHostKeyChecking=no root@65.108.2.208 /bin/bash << 'EOL'
            echo "Successfully connected to the public server!"
            
            # Create second key file
            echo "${{ secrets.SECOND_PRIVATE_KEY }}" > ~/.ssh/id_rsa_second
            chmod 600 ~/.ssh/id_rsa_second
            
            # Connect to private server and restart the Docker container
            ssh -tt -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_second root@192.168.37.78 "
              echo 'Successfully connected to private server!'
              echo 'Restarting Docker container 922c1fa1dcb7...'
              docker restart 922c1fa1dcb7
              echo 'Waiting for container to restart...'
              sleep 5
              docker ps | grep 922c1fa1dcb7
            "
            
            exit
          EOL
