name: Test Runner Connection

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: self-hosted  # This ensures it uses your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test connection
        run: echo "GitHub Actions Runner is working!"
